rust: Upgrade 1.74.1 -> 1.75.0
Drop backported musl fixes. Set `change-id` rather than `changelog-seen`
to fix build warning. Add fixes for 85c0ce24cc74 ("remap cargo
dependencies to /rust/deps") which otherwise cause build failures:

| thread 'main' panicked at src/core/builder.rs:1795:26:
| std::fs::read_dir(registry_src) failed with No such file or directory (os error 2)

https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html
Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>