rust: Upgrade 1.73.0 -> 1.74.0
Drop hardcodepaths.patch (equivalent fix merged upstream), add backports
for musl fixes.

Drop TARGET_VENDOR export which was used by crossbeam_atomic.patch, but was
removed as part of the 1.69.0 upgrade.

Add sysconfdir to config.toml to fix:

| thread 'main' panicked at install.rs:92:9:
| User doesn't have write access on `install.sysconfdir` path in `config.toml`.

Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>